'use strict';
let lang=localStorage.getItem('yuhe-language')||'zh';
let content={projects:[],resume:[]},selected=null,panel='welcome';
const $=s=>document.querySelector(s),main=$('#main'),viewer=$('#viewer');
const tr=(zh,en)=>lang==='zh'?zh:en;
const t=o=>typeof o==='string'?o:o?.[lang]||o?.zh||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cats=[
 {id:'media',name:{zh:'工作记录',en:'Work Records'},en:'WORK RECORDS',disc:'blue',symbol:'◌',intro:{zh:'能完成账号内容选题、文案撰写、镜头设计与视频剪辑，兼顾传播与转化。营销视频获得高流量，KOC与信息流视频突出转化效果，并通过数据记录复盘内容表现。',en:'I develop account content from topic selection and copywriting to shot design and editing, balancing reach and conversion. My marketing videos attract high traffic, while KOC and feed ads focus on conversion, with performance tracked for review.'}},
 {id:'film',name:{zh:'视频与影像',en:'Film & video'},en:'FILM & VIDEO',disc:'star',symbol:'✧',intro:{zh:'能参与策划编导、采访、拍摄与剪辑，完成纪录片、微电影广告及动画合成等作品。把实地观察与创作思路转化为连贯的影像叙事，让人物故事、文化内容与产品理念得到具体呈现。',en:'I contribute to planning, directing, interviews, filming and editing across documentaries, short film ads and animation composites. I turn field observations and creative ideas into coherent visual stories that bring people, culture and product concepts to life.'}},
 {id:'writing',name:{zh:'文案与策划',en:'Writing & planning'},en:'WRITING & IDEAS',disc:'pink',symbol:'✦',intro:{zh:'能撰写新闻、解说、剧本与活动方案，也能进行产品策划和传播策略分析。根据不同受众组织信息，把创意梳理成清晰的故事、内容结构与执行思路，为拍摄、活动和产品设计提供依据。',en:'I write news, narration, scripts and activity proposals, and develop product concepts and communication analyses. I organize information for different audiences, shaping ideas into clear stories, content structures and plans that guide filming, activities and product design.'}},
 {id:'design',name:{zh:'产品与设计',en:'Product & design'},en:'PRODUCT & DESIGN',disc:'heart',symbol:'♡',intro:{zh:'能结合资料搜集、数据抓取、文案写作与视觉设计，制作H5交互图文、海报及文创角色。通过信息编排、画面风格与交互设计，把复杂话题讲得直观易读，让内容表达与视觉呈现相互配合。',en:'I combine research, data collection, writing and visual design to create interactive H5 stories, posters and cultural character designs. Information structure, visual style and interaction make complex topics easier to follow and align the message with its presentation.'}}
];
function machineButton(label,action,icon=''){return `<button class="machine-btn" data-panel="${action}">${icon?`<span aria-hidden="true">${icon}</span>`:''}${label}</button>`}
function screenContent(){
 const meta=`<div class="screen-meta"><span><i class="led"></i>${selected?'DISC '+String(cats.findIndex(c=>c.id===selected)+1).padStart(2,'0')+' / SELECTED':'YUHE / PERSONAL PORTFOLIO'}</span><span>CLASS OF 2027 · STEREO</span></div>`;
 if(selected){const c=cats.find(c=>c.id===selected);return meta+`<div class="eyebrow" style="color:#b69dbb;margin-bottom:12px">${c.en}</div><h1>${t(c.name)}</h1><p class="intro">${t(c.intro)}</p><p class="identity">${content.projects.filter(p=>p.categories.includes(c.id)).length} ${tr('个项目 · 持续更新','projects · continually evolving')}</p>`}
 if(panel==='about')return meta+`<h2>${tr('关于杨雨荷','About Yuhe')}</h2><p class="inline-about">${tr('天津师范大学广播电视学专业，2027届。我的实践涵盖新媒体运营、视频制作、文案策划与视觉设计，热于拥抱新事物，也喜欢把想法变成具体的作品。','A Radio and Television student at Tianjin Normal University, graduating in 2027. My work spans new media, video, writing and visual design. I enjoy learning new things and turning ideas into tangible work.')}</p><p class="inline-about" style="margin-top:14px"><strong>${tr('实践经历','Experience')}</strong> · ${tr('华汽研究院、天津笔尖文化传媒有限公司、天津电视台。','Hu aqi Research Institute, Tianjin Bijian Culture Media and Tianjin Television.').replace('Hu aqi','Huaqi')}</p><p class="identity">${tr('学习力 / 生命力 / 创造力','CURIOSITY / VITALITY / CREATIVITY')}</p>`;
 if(panel==='contact')return meta+`<h2>${tr('很高兴与你联系','Let’s get in touch')}</h2><a class="contact-big" href="mailto:2154368849@qq.com">2154368849@qq.com ↗</a><p class="intro" style="margin-top:18px">${tr('欢迎交流作品，也期待新的实践机会。','Open to conversations about creative work and new opportunities.')}</p>`;
 if(panel==='resume')return meta+`<h2>${tr('我的简历','My résumé')}</h2><p class="intro">${tr('杨雨荷 · 2027届 · 天津师范大学广播电视学','Yang Yuhe · Class of 2027 · Radio and Television, Tianjin Normal University')}</p><div class="screen-resume-actions"><button class="machine-btn" data-resume>${tr('查看简历','View résumé')} ↗</button><a class="machine-btn" href="assets/yang-yuhe-resume.docx" download="杨雨荷_简历.docx">${tr('下载简历','Download résumé')} ↓</a></div>`;
 return meta+`<h1>${tr('欢迎来到我的网站','Welcome to my world')}</h1><p class="quote">${tr('单击cd查看详情，双击进入集合','Click a CD for details; double-click to open its collection.')}<span class="hint-stars" aria-hidden="true">✦ ✧ ✦</span></p><p class="intro">${tr('我是杨雨荷。我的实践涵盖账号运营、视频制作、策划编导、文案策划与视觉设计，热于拥抱新事物，也有许多想法为了让热爱延续，我会持续提升自己，在这里，我记录作品，也记录从选题到制作过程中的思考与尝试','I’m Yang Yuhe. My work spans social media account management, video production, creative planning and directing, copywriting, and visual design. I embrace new things and have plenty of ideas. To keep doing what I love, I continue to develop my skills. Here, I document my work and the thoughts and experiments behind it, from choosing a topic to production.')}</p><p class="identity"><span class="screen-name">${tr('杨雨荷','YANG YUHE')}</span>${tr('2027届 · 天津师范大学广播电视学','CLASS OF 2027 · TIANJIN NORMAL UNIVERSITY')}</p>`;
}
function home(){
 main.innerHTML=`<section class="player" aria-label="${tr('CD机作品目录','CD player portfolio directory')}"><div class="machine-top"><div class="dial" aria-hidden="true"><div class="knob"></div><div class="knob-small"></div></div><div class="screen-frame"><div class="screen" id="display" aria-live="polite">${screenContent()}</div><span class="frame-star star-one" aria-hidden="true">✦</span><span class="frame-star star-two" aria-hidden="true">✦</span><span class="frame-star star-three" aria-hidden="true">✦</span></div><div class="lights" aria-hidden="true"><i></i><i></i><i></i></div></div><nav class="controls" aria-label="${tr('播放器控制','Player controls')}"><div class="button-set">${machineButton(tr('首页','Home'),'welcome','⌂')}${machineButton(tr('关于我','About'),'about','✧')}${machineButton(tr('查看简历','Résumé'),'resume','▤')}${machineButton(tr('联系我','Contact'),'contact','↗')}<a class="machine-btn" href="#/other"><span aria-hidden="true">⊞</span>${tr('其他作品','Other work')}</a></div><button class="machine-btn primary machine-open" id="open-disc" ${selected?'':'disabled'}>▶ ${selected?tr('打开作品集','Open collection'):tr('选择一张CD','Select a CD')}</button></nav><div class="bay-head"><span>MY COLLECTION / 01—04</span><span>${tr('把想法刻录成作品','IDEAS, RECORDED.')}</span></div><div class="disc-bay">${cats.map((c,i)=>`<button class="disc-button ${selected===c.id?'selected':''}" data-disc="${c.id}" aria-pressed="${selected===c.id}" aria-label="${tr('选择','Select')} ${t(c.name)}"><span class="disc-art"><span class="disc-fallback" aria-hidden="true"><span>${c.symbol}</span></span><img src="assets/cd-${c.disc}.${['pink','heart'].includes(c.disc)?'svg':'png'}" alt="" data-disc-art onerror="this.hidden=true" onload="this.previousElementSibling.hidden=true"></span><span class="disc-label">${t(c.name)}</span><span class="disc-num">0${i+1} / ${c.en}</span></button>`).join('')}</div></section><p class="disc-hint"><span aria-hidden="true">↖</span><span class="desktop-hint">${tr('点选CD，双击打开，或点击「打开作品集」','Select a CD, double-click to open, or press Open collection')}</span><span class="mobile-hint">${tr('点选CD，双击打开，或点击「打开作品集」','Select a CD, double-click to open, or press Open collection')}</span></p><div class="home-bottom"><div class="values"><span>${tr('学习力','Curiosity')}</span><span>${tr('生命力','Vitality')}</span><span>${tr('创造力','Creativity')}</span></div><p>MADE OF THOUGHTS, TRIALS & LITTLE MAGIC ✧</p></div>`;
 document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{selected=null;panel=b.dataset.panel;updatePlayer()});
 document.querySelectorAll('[data-disc]').forEach(b=>{b.onclick=()=>{selected=b.dataset.disc;updatePlayer()};b.ondblclick=()=>location.hash='/category/'+b.dataset.disc});
 $('#open-disc').onclick=()=>{if(selected)location.hash='/category/'+selected};bindResume();
}
function updatePlayer(){
 $('#display').innerHTML=screenContent();document.querySelectorAll('[data-disc]').forEach(b=>{b.classList.toggle('selected',b.dataset.disc===selected);b.setAttribute('aria-pressed',b.dataset.disc===selected)});
 const open=$('#open-disc');open.disabled=!selected;open.textContent='▶ '+(selected?tr('打开作品集','Open collection'):tr('选择一张CD','Select a CD'));bindResume();
}
function breadcrumb(name){return `<nav class="breadcrumbs"><a href="#/">${tr('首页','Home')}</a><span>/</span><span>${esc(name)}</span></nav>`}
function head(title,intro,eyebrow,count){return `<div class="page-heading"><div class="page-heading-inner"><span class="eyebrow">${eyebrow}</span>${count!==undefined?`<span class="count">${count} ${tr('个项目','PROJECTS')}</span>`:''}<h1>${esc(title)}</h1><p>${esc(intro)}</p><nav class="section-nav">${cats.map(c=>`<a href="#/category/${c.id}">${t(c.name)}</a>`).join('')}<a href="#/other">${tr('其他作品','Other work')}</a></nav></div></div>`}
function meta(p){return `<div class="work-meta">${[...(p.tags||[]).map(t),t(p.role),p.date,t(p.nature)].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')}</div>`}
function preview(p,index=0){
 const m=p.materials[index],video=m?.type==='video';const poster=video?m.poster:m?.type==='image'?m.src:p.cover;
 return `<div class="media-shell ${video?'tv':'folder'}"><button class="preview-button" data-preview="${p.id}" data-index="${index}" aria-label="${esc(tr('打开预览：','Preview: ')+t(p.title))}">${poster?`<img src="${esc(poster)}" alt="${esc(t(p.title))}" loading="lazy">`:`<span class="paper-cover"><small>${m?.type==='data'?'DATA & OBSERVATION':m?.type==='link'?'INTERACTIVE / H5':'IDEAS ON PAPER'}</small><strong>${esc(t(p.title))}</strong><span class="paper-star" aria-hidden="true">✧</span></span>`}<span class="play-icon" aria-hidden="true">${video?'▶':'↗'}</span></button><span class="device-label" aria-hidden="true">YUHE · VISION / PLAY</span></div>`;
}
function workList(ps,id){return `<div class="work-list">${ps.map((p,i)=>`<article class="work-card" id="work-${p.id}">${preview(p,id==='writing'?Math.max(0,p.materials.findIndex(m=>['document','slides'].includes(m.type))):0)}<div class="work-info"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${cats.find(c=>c.id===id).en}</span><h2><a href="#/work/${p.id}">${esc(t(p.title))}</a></h2><p class="summary">${esc(t(p.summary))}</p>${p.notice?`<p class="media-notice">${esc(t(p.notice))}</p>`:''}${meta(p)}<a class="detail-link" href="#/work/${p.id}">${tr('作品介绍与创作记录','Project & creative notes')} ↗</a></div></article>`).join('')}</div>`}
function folderCard(f){return `<a class="work-folder" href="#/folder/${esc(f.id)}"><span class="folder-drawing" aria-hidden="true">✦</span><div><span class="eyebrow">VIDEO COLLECTION / ${f.projects.length}</span><h2>${esc(t(f.title))}</h2><p>${esc(t(f.summary))}</p><span class="detail-link">${tr('单击打开文件夹','Open folder')} ↗</span></div></a>`}
function category(id){const c=cats.find(c=>c.id===id);if(!c)return notFound();const fs=(content.folders||[]).filter(f=>f.category===id),grouped=new Set(fs.flatMap(f=>f.projects));const all=content.projects.filter(p=>p.categories.includes(id));const ps=all.filter(p=>!grouped.has(p.id)).sort((a,b)=>a.order-b.order);main.innerHTML=breadcrumb(t(c.name))+head(t(c.name),t(c.intro),c.en,all.length)+fs.map(folderCard).join('')+workList(ps,id)+updating();bindPreviews()}
function folder(id){const f=(content.folders||[]).find(f=>f.id===id);if(!f)return notFound();const ps=f.projects.map(id=>content.projects.find(p=>p.id===id)).filter(Boolean);main.innerHTML=breadcrumb(t(f.title))+head(t(f.title),t(f.summary),'VIDEO COLLECTION',ps.length)+`<a class="collection-back" href="#/category/${f.category}">← ${tr('返回上一页 · ','Back to ')}${t(cats.find(c=>c.id===f.category).name)}</a>`+workList(ps,f.category)+updating();bindPreviews()}

function sourceNote(){return lang==='en'?'<p class="source-lang">Original material is presented in Chinese.</p>':''}
function tableHTML(table){return `<div class="table-wrap swot-table"><table><thead><tr>${table.headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${table.rows.map(r=>`<tr><th scope="row">${esc(r[0])}</th><td>${esc(r[1])}</td></tr>`).join('')}</tbody></table></div>`}
function paragraphHTML(p){return typeof p==='string'?`<p>${esc(p)}</p>`:`<h3>${esc(p.heading||'')}</h3>${tableHTML(p.table)}`}
function downloadHTML(p){return (p.downloads||[]).map(d=>`<a class="machine-btn" href="${esc(d.src)}" download="${esc(d.name)}">${esc(t(d.title))} ↓</a>`).join('')}
function documentHTML(m){return `<div class="reading-body">${sourceNote()}${m.paragraphs.map(paragraphHTML).join('')}</div>`}
function slidesHTML(m){return `<div class="reading-body">${sourceNote()}<div class="slides">${m.slides.map(s=>`<section class="slide-page"><div class="slide-number">${tr('方案内容','PRESENTATION CONTENT')} / ${String(s.number).padStart(2,'0')}</div>${s.text.map((p,i)=>i===0?`<h3>${esc(p)}</h3>`:`<p>${esc(p)}</p>`).join('')}${s.table?tableHTML(s.table):''}<div class="slide-images">${s.images.map(src=>`<img src="${esc(src)}" alt="${tr('方案配图','Presentation visual')}" loading="lazy">`).join('')}</div></section>`).join('')}</div></div>`}
function dataHTML(m){return `<p class="media-notice">${esc(t(m.note))}</p><div class="table-wrap"><table><thead><tr>${(lang==='en'?['Date','Views','Recommendations','Likes','Comments','Shares','Follows']:m.rows[0]).map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${m.rows.slice(1).map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function linkHTML(m){return `<article class="interactive-story"><a class="link-box" href="${esc(m.url)}" target="_blank" rel="noopener noreferrer"><span>${esc(t(m.title))}</span><span>${tr('打开交互作品','Open interactive work')} ↗</span></a>${m.summary?`<p class="story-summary">${esc(t(m.summary))}</p>`:''}${m.emphasis?`<p class="story-emphasis"><strong>${esc(t(m.emphasis))}</strong></p>`:''}${m.behindScenes?`<a class="detail-link" href="${esc(m.behindScenes.url)}" target="_blank" rel="noopener noreferrer">${esc(t(m.behindScenes.title))} ↗</a>`:''}</article>`}

function detail(id){const p=content.projects.find(p=>p.id===id);if(!p)return notFound();main.innerHTML=breadcrumb(t(p.title))+head(t(p.title),t(p.summary),'PROJECT / '+String(p.order+1).padStart(2,'0'))+`<article class="detail-layout">${p.notice?`<p class="media-notice">${esc(t(p.notice))}</p>`:''}${meta(p)}<div class="detail-actions">${downloadHTML(p)}${p.categories.map(id=>`<a class="machine-btn" href="#/category/${id}">← ${t(cats.find(c=>c.id===id).name)}</a>`).join('')}</div>${p.materials.map((m,i)=>`<section class="material">${['video','image'].includes(m.type)?preview(p,i):m.type==='document'?`<details class="reading"><summary>${esc(t(m.title))} · ${tr('阅读全文','Read')}</summary>${documentHTML(m)}</details>`:m.type==='slides'?`<details class="reading"><summary>${esc(t(m.title))} · ${tr('查看方案','Read proposal')}</summary>${slidesHTML(m)}</details>`:m.type==='data'?`<div class="reading"><h2>${esc(t(m.title))}</h2>${dataHTML(m)}</div>`:linkHTML(m)}</section>`).join('')}${p.notes?.length?`<section class="notes"><h2>${tr('创作注释','Creative notes')}</h2>${p.notes.map(n=>`<p>${esc(t(n))}</p>`).join('')}</section>`:''}</article>`;bindPreviews()}
function updating(){return `<p class="collection-update">✧ ${tr('持续更新中','Continuously updated')}</p>`}
function other(){main.innerHTML=breadcrumb(tr('其他作品','Other work'))+head(tr('其他作品','Other work'),tr('留给新的尝试，也留给尚未归类的灵感，多为爱好与小特长，可选择性辅助浏览','A space for new experiments and ideas that don’t fit a category, mostly hobbies and small talents for optional supplementary browsing.'),'OTHER COLLECTIONS')+`<div class="other-collections">${(content.collections||[]).map(c=>`<a class="hobby-card" href="#/collection/${esc(c.id)}"><img class="floppy-icon" src="${esc(c.icon)}" alt=""><div><span class="eyebrow">COLLECTION / ${String((content.collections||[]).indexOf(c)+1).padStart(2,'0')}</span><h2>${esc(t(c.title))}</h2><p>${esc(t(c.summary))}</p><span class="detail-link">${esc(t(c.note))} ↗</span></div></a>`).join('')}</div>`+updating()}
function collection(id){const c=(content.collections||[]).find(c=>c.id===id);if(!c)return notFound();if(c.workbooks)return workbookCollection(c);if(c.downloads)return downloadCollection(c);main.innerHTML=breadcrumb(t(c.title))+head(t(c.title),t(c.summary),'PERSONAL SKETCHBOOK')+`<a class="collection-back" href="#/other">← ${tr('返回上一页 · 其他作品','Back to Other work')}</a><div class="hobby-gallery">${c.images.map((src,i)=>`<button class="hobby-art" data-hobby-image="${i}" aria-label="${tr('放大查看示例','Enlarge example')} ${i+1}"><img src="${esc(src)}" alt="${esc(t(c.title))} · ${tr('示例','Example')} ${i+1}" loading="lazy"><span>${String(i+1).padStart(2,'0')} / ${tr('单击放大','Click to enlarge')} ↗</span></button>`).join('')}</div>`+updating();document.querySelectorAll('[data-hobby-image]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.hobbyImage);openViewer(t(c.title)+' · '+String(i+1).padStart(2,'0'),`<img src="${esc(c.images[i])}" alt="${esc(t(c.title))} · ${i+1}">`)})}

function notFound(){main.innerHTML=`<section class="empty"><h1>${tr('未找到这个页面','Page not found')}</h1><a class="detail-link" href="#/">${tr('回到首页','Back home')}</a></section>`}
function openViewer(title,html){$('#viewer-title').textContent=title;$('#viewer-body').innerHTML=html;viewer.showModal();$('#viewer-body').scrollTop=0;document.body.style.overflow='hidden'}
function closeViewer(){viewer.querySelectorAll('video').forEach(v=>v.pause());viewer.close();document.body.style.overflow='';$('#viewer-body').innerHTML=''}
function bindPreviews(){document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{const p=content.projects.find(p=>p.id===b.dataset.preview),m=p.materials[Number(b.dataset.index)];
 if(m.type==='video'){
  openViewer(t(p.title),`<video controls playsinline preload="metadata" controlslist="nodownload" poster="${esc(m.poster||'')}"><source src="${esc(m.src)}" type="video/mp4"></video><p class="media-notice">${esc(t(p.summary))}</p>`);
  const v=viewer.querySelector('video');v.addEventListener('play',()=>{autoMusicPending=false;bgm.pause();syncMusic()});autoMusicPending=false;bgm.pause();syncMusic();v.addEventListener('error',()=>{v.insertAdjacentHTML('afterend',`<p class="media-error">${tr('这份视频暂时无法播放，作品介绍与文稿仍可查看。','This video is currently unavailable. The project description and written materials remain accessible.')}</p>`)},{once:true});v.play().catch(()=>{});
 }else if(m.type==='image')openViewer(t(p.title),`<img src="${esc(m.src)}" alt="${esc(t(p.title))}">`);
 else if(m.type==='document')openViewer(t(p.title),documentHTML(m));
 else if(m.type==='slides')openViewer(t(p.title),downloadHTML(p)+slidesHTML(m));
 else if(m.type==='data')openViewer(t(p.title),dataHTML(m));
 else if(m.type==='link')openViewer(t(p.title),p.materials.filter(m=>m.type==='link').map(linkHTML).join(''));
})}
function bindResume(){document.querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>openViewer(tr('杨雨荷 · 简历','Yang Yuhe · Résumé'),`<div class="resume-tools"><a class="machine-btn primary" href="assets/yang-yuhe-resume.docx" download="杨雨荷_简历.docx">${tr('下载简历','Download résumé')} ↓</a><p>${tr('以下为简历内容阅读版，下载文件保留原版排版。','Text reading view below. The download preserves the original document layout.')}</p></div><div class="resume-paragraphs">${content.resume.map(p=>`<p class="${['基本信息','教育经历','实习经历','项目与校园经历','专业技能'].includes(p)?'resume-heading':''}">${esc(p)}</p>`).join('')}</div>`))}
$('#viewer-close').onclick=closeViewer;viewer.addEventListener('cancel',e=>{e.preventDefault();closeViewer()});viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeViewer()}});
function render(){if(viewer.open)closeViewer();document.documentElement.lang=lang==='zh'?'zh-CN':'en';$('#language').textContent=lang==='zh'?'EN ↗':'中文 ↗';$('#language').setAttribute('aria-label',tr('Switch to English','切换到中文'));$('#home-link').textContent=tr('回到首页','Back home');$('#footer-note').textContent=tr('持续创作，持续更新。','Always creating. Always evolving.');const parts=(location.hash.slice(1)||'/').split('/').filter(Boolean);if(!parts.length)home();else if(parts[0]==='category')category(parts[1]);else if(parts[0]==='work')detail(parts[1]);else if(parts[0]==='other')other();else if(parts[0]==='collection')collection(parts[1]);else if(parts[0]==='folder')folder(parts[1]);else notFound();renderMusic();document.title=tr('欢迎来到我的网站 · 杨雨荷','Yang Yuhe · Personal Portfolio')}
$('#language').onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('yuhe-language',lang);render()};
$('.skip').onclick=e=>{e.preventDefault();main.focus();main.scrollIntoView()};
document.addEventListener('click',e=>{const a=e.target.closest('a[href="#/"]');if(a){selected=null;panel='welcome';if(!location.hash||location.hash==='#/'){home();renderMusic();window.scrollTo(0,0)}}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);main.focus({preventScroll:true})});
fetch('content.json').then(r=>{if(!r.ok)throw Error('Content unavailable');return r.json()}).then(data=>{content=data;render()}).catch(()=>{main.innerHTML=`<section class="empty"><h1>作品集暂未加载 / Unable to load</h1><p>请刷新页面重试。 / Please refresh to try again.</p></section>`});
const bgm=new Audio();bgm.preload='metadata';bgm.loop=true;bgm.volume=.35;
const tracks=[{src:'assets/bgm-1.mp3',zh:'音乐 01',en:'Track 01'},{src:'assets/bgm-2.mp3',zh:'音乐 02',en:'Track 02'}];
let trackIndex=0,musicExpanded=false,musicError='',musicAttempt=0,autoMusicPending=true;bgm.src=tracks[0].src;
function syncMusic(){document.querySelectorAll('[data-music-toggle]').forEach(b=>{b.textContent=bgm.paused?tr('♫ 开启','♫ Play'):tr('Ⅱ 关闭','Ⅱ Pause');b.setAttribute('aria-pressed',String(!bgm.paused))});document.querySelectorAll('[data-music-volume]').forEach(i=>i.value=bgm.volume);document.querySelectorAll('.music-status').forEach(e=>e.textContent=musicError||(bgm.paused?tr('音乐已关闭','Music is off'):tr('正在播放 · '+tracks[trackIndex].zh,'Playing · '+tracks[trackIndex].en)));}
async function toggleMusic(){autoMusicPending=false;musicError='';if(!bgm.paused){musicAttempt++;bgm.pause()}else{document.querySelectorAll('video').forEach(v=>v.pause());const attempt=++musicAttempt;try{await bgm.play()}catch(e){if(attempt===musicAttempt&&e.name!=='AbortError')musicError=tr('播放未成功，请再试一次。','Playback failed. Please try again.')}}syncMusic()}
function renderMusic(){
 const isHome=!(location.hash.slice(1)||'/').split('/').filter(Boolean).length;
 document.querySelectorAll('.music-dock,.music-mini').forEach(e=>e.remove());
 if(isHome){main.insertAdjacentHTML('beforeend',`<aside class="music-dock" aria-label="${tr('背景音乐','Background music')}"><button class="earbuds-button" id="earbuds" aria-expanded="${musicExpanded}" aria-controls="music-panel" aria-label="${tr('打开音乐设置','Open music settings')}" title="${tr('音乐设置','Music settings')}"><img src="assets/earbuds.png" alt="" aria-hidden="true"><span class="music-label">${tr('音乐','Music')}</span></button><button class="music-quick" data-music-toggle></button><div class="music-panel" id="music-panel" ${musicExpanded?'':'hidden'}><label for="music-track">${tr('切换音乐','Choose music')}</label><select id="music-track">${tracks.map((x,i)=>`<option value="${i}" ${i===trackIndex?'selected':''}>${x[lang]}</option>`).join('')}</select><button class="machine-btn" data-music-toggle></button><label>${tr('音量','Volume')}<input data-music-volume type="range" min="0" max="1" step=".01" value="${bgm.volume}"></label><p class="music-status" role="status"></p></div></aside>`);$('#earbuds').onclick=()=>{musicExpanded=!musicExpanded;$('#music-panel').hidden=!musicExpanded;$('#earbuds').setAttribute('aria-expanded',musicExpanded)};$('#music-track').onchange=async e=>{const playing=!bgm.paused;musicAttempt++;bgm.pause();trackIndex=Number(e.target.value);bgm.src=tracks[trackIndex].src;musicError='';if(playing)await toggleMusic();syncMusic()};
 }else{$('.top-actions').insertAdjacentHTML('beforeend',`<div class="music-mini"><button data-music-toggle></button><input data-music-volume type="range" min="0" max="1" step=".01" value="${bgm.volume}" aria-label="${tr('背景音乐音量','Background music volume')}"></div>`)}
 document.querySelectorAll('[data-music-toggle]').forEach(b=>b.onclick=toggleMusic);document.querySelectorAll('[data-music-volume]').forEach(i=>i.oninput=()=>{bgm.volume=Number(i.value);syncMusic()});syncMusic();
}
bgm.addEventListener('pause',syncMusic);bgm.addEventListener('play',syncMusic);bgm.addEventListener('error',()=>{musicError=tr('音乐加载失败，请切换另一首。','Music could not load. Please choose another track.');syncMusic()});

// Try audible autoplay once. When blocked, retry on a trusted user interaction.
async function startDefaultMusic(){
 if(!autoMusicPending)return;
 if([...document.querySelectorAll('video')].some(v=>!v.paused)){autoMusicPending=false;return}
 try{await bgm.play();autoMusicPending=false;musicError=''}catch(e){if(e.name==='NotAllowedError'){musicError=tr('点击页面后开始播放','Music starts when you interact')}else{autoMusicPending=false;musicError=tr('音乐暂时无法播放','Music is currently unavailable')}}syncMusic();
}
const clickSound=new Audio('assets/button-click.mp3');clickSound.preload='auto';clickSound.volume=.45;
document.addEventListener('click',e=>{
 const button=e.target.closest('button,a,summary');
 if(button&&!button.disabled){clickSound.currentTime=0;clickSound.play().catch(()=>{})}
 if(autoMusicPending&&!e.target.closest('[data-music-toggle],[data-preview]'))startDefaultMusic();
},true);
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&autoMusicPending&&!e.target.closest('[data-music-toggle],[data-preview]'))startDefaultMusic()});
startDefaultMusic();
document.addEventListener('click',e=>{if(musicExpanded&&!e.target.closest('.music-dock')){musicExpanded=false;const p=$('#music-panel');if(p)p.hidden=true;$('#earbuds')?.setAttribute('aria-expanded','false')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&musicExpanded){musicExpanded=false;const p=$('#music-panel');if(p)p.hidden=true;$('#earbuds')?.setAttribute('aria-expanded','false');$('#earbuds')?.focus()}});



function workbookCollection(c){main.innerHTML=breadcrumb(t(c.title))+head(t(c.title),t(c.summary),'DATA COLLECTION')+`<a class="collection-back" href="#/other">← ${tr('返回上一页 · 其他作品','Back to Other work')}</a><div class="workbook-list">${c.workbooks.map((w,i)=>`<button class="workbook-open" data-workbook="${i}"><span aria-hidden="true">▦</span><strong>${esc(t(w.title))}</strong><span>${tr('单击查看表格','View spreadsheet')} ↗</span></button>`).join('')}</div>`+updating();document.querySelectorAll('[data-workbook]').forEach(b=>b.onclick=async()=>{const w=c.workbooks[Number(b.dataset.workbook)];openViewer(t(w.title),`<p>${tr('正在加载表格…','Loading spreadsheet…')}</p>`);try{const res=await fetch(w.src);if(!res.ok)throw Error();const sheets=await res.json();if(!viewer.open||$('#viewer-title').textContent!==t(w.title))return;let sheet=0,page=0;function draw(){const rows=sheets[sheet].rows,body=rows.slice(1),pages=Math.max(1,Math.ceil(body.length/30));$('#viewer-body').innerHTML=`<div class="sheet-toolbar"><label>${tr('工作表','Sheet')} <select id="sheet-choice">${sheets.map((s,i)=>`<option value="${i}" ${i===sheet?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><span>${body.length} ${tr('条记录','records')}</span></div><div class="table-wrap crawler-table"><table><thead><tr>${(rows[0]||[]).map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${body.slice(page*30,page*30+30).map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="sheet-pages"><button class="machine-btn" id="sheet-prev" ${page===0?'disabled':''}>← ${tr('上一页','Previous')}</button><span>${page+1} / ${pages}</span><button class="machine-btn" id="sheet-next" ${page+1===pages?'disabled':''}>${tr('下一页','Next')} →</button></div>`;$('#sheet-choice').onchange=e=>{sheet=Number(e.target.value);page=0;draw()};$('#sheet-prev').onclick=()=>{page--;draw()};$('#sheet-next').onclick=()=>{page++;draw()};}draw()}catch{$('#viewer-body').innerHTML=`<p>${tr('表格加载失败，请关闭后重试。','Unable to load. Please close and try again.')}</p>`}})}

function downloadCollection(c){main.innerHTML=breadcrumb(t(c.title))+head(t(c.title),t(c.summary),'PRESENTATIONS')+`<a class="collection-back" href="#/other">← ${tr('返回上一页 · 其他作品','Back to Other work')}</a><div class="workbook-list">${c.downloads.map(d=>`<a class="workbook-open" href="${esc(d.src)}" download="${esc(d.name)}"><span aria-hidden="true">▤</span><strong>${esc(t(d.title))}</strong><span>${tr('下载原 PPT','Download PPT')} ↓</span></a>`).join('')}</div>`+updating()}
